vita-epfl/I_like_trains

client/agent.py
These might confuse students if they don't understand that these are only suggestions.
=> Remove the method ideas

README.md, client/agent.py, client/base_agent.py, client/client.py, client/event_handler.py, client/game_state.py, client/network.py, client/renderer.py, config.json, server/ai_client.py, server/delivery_zone.py, server/game.py, server/server.py, server/train.py
- Hiding very quick apparition of "Press SPACE to spawn" message when ready to respawn
- Removed commented logs and cleaned logs
- Handling death of other train when colliding. Added kill() function in train
- Added an enum controltype "control_mode" in json instead of "ACTIVATE_AGENT" and "MANUAL_CONTROL"
=> New update

client/client.py
note: this is a stacked diff, please review and merge https://github.com/vita-epfl/I_like_trains/pull/32 first.
=> Print an error message if config.json is invalid

.vscode/launch.json, README.md, client/__init__.py, client/__main__.py, client/agent.py, client/base_agent.py, client/client.py, server/__main__.py, server/ai_client.py, server/game.py, server/room.py, server/server.py, single_process/README.md, single_process/__main__.py
This enables pausing the server when the client hits a breakpoint.
Using multiple __main__.py files is the proper way to have multiple command line files. Notice how we get rid of the ugly hack in server/ai_client.py.
Fixes https://github.com/vita-epfl/I_like_trains/issues/26
=> Add single_process/__main__.py

README.md, client/client.py, client/renderer.py, common/client_config.py, common/config.py, common/server_config.py, config.json, server/__main__.py, server/ai_client.py, server/delivery_zone.py, server/game.py, server/passenger.py, server/room.py, server/server.py, single_process/__main__.py
I'm refactoring how the config.json gets used.
See https://github.com/vita-epfl/I_like_trains/issues/36
=> Refactor Config

client/agent.py
Better reflect the fact that this is a two-student project.
=> Change SCIPERS to have two sample scipers

client/base_agent.py
Also fixes an incomplete comment.
=> Log on incorrect return from agent's get_move() method

client/client.py, server/ai_client.py, server/server.py
Comments shouldn't start with "# add" unless something is actually being added.
=> Improve some comments

client/base_agent.py, client/client.py, client/event_handler.py, client/game_state.py
=> Fix "Failed to send UDP message: Object of type Move is not JSON serializable" bug

server/room.py
=> Replace `random.randint(0, len(self.config.agents) - 1)` with `random.choice(...)`

README.md
=> New readme for new config

README.md
Reverts vita-epfl/I_like_trains#89
=> Revert "New readme for new config"

server/room.py
- pick a random subset of available agents when we need few additional bots
- pick each agent once or more if we need more additional bots
=> Improve bot selection

client/client.py, client/game_state.py, client/network.py, server/game.py, server/server.py, server/train.py
bool boost_cooldown_active now accessible in agent.py through train_data. Switched boost cooldown calculation back to seconds intead of tick amount for more precision. Removed "handle_drop_wagon_success". Fixed wagon not dropped if alone in the train. Fixes #76 #77 and #120
=> Boost cooldown updated

README.md, client/client.py, client/network.py, common/client_config.py, common/server_config.py, server/server.py, simulate_clients.ps1
Introducting simulate_clients.ps1 and add_suffix_to_nickname parameter. Added explainations in Readme
=> Simulate many clients easily

server/ai_client.py, server/game.py, server/room.py, server/server.py, server/train.py
=> Fixed ai_agent initlization when client disconnects

client/network.py
=> Updated the way the network manages socket messages

client/game_state.py, server/game.py, server/server.py, server/train.py
=> Added death callback

README.md
=> Added doc about config.py and how to upgrade

client/client.py, common/client_config.py, server/game.py, server/passenger.py, server/room.py, server/server.py
=> Simplified game initialisation logic

.gitignore, common/stats_manager.py, requirements.txt, server/ai_client.py, server/game.py, server/room.py, server/server.py
Added the following tables:
-bot_vs_human_last_scores  
-connections_daily
-connections_log
-clients
-connections_hourly
The database is stored in a folder "stats"
=> Added database with stats about the server

server/server.py
Raises an error if the file does not exist. Should fix #170
=> Verifies the bot files before launching the server

client/client.py, client/network.py
=> Removed invalid log "Successfully connected to server"

common/server_config.py, config.json.template, docs/game-modes.md, server/ai_client.py, server/server.py
"random" option for nb_players_per_room takes a random nb_players_per_room between 2 and 4.
Would fix #187
=> "random" option for nb_players_per_room
